# Generated by Django 4.1.7 on 2023-04-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_details', '0002_alter_education_cgpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='details',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
