# Generated by Django 4.1.7 on 2023-04-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_details', '0003_alter_skills_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiance',
            name='details',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
