# Generated by Django 4.1.7 on 2023-04-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_details', '0004_alter_experiance_details_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='rate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
