# Generated by Django 4.1.7 on 2023-04-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_details', '0005_skills_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiance',
            name='details',
            field=models.CharField(max_length=500),
        ),
    ]
