# Generated by Django 4.1.7 on 2023-04-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_details', '0006_alter_experiance_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='course',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='address',
            field=models.CharField(max_length=500),
        ),
    ]
