# Generated by Django 4.1.7 on 2023-04-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_details', '0007_education_course_alter_basicdetails_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='certificate_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='duration',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='details',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
