# Generated by Django 4.1.7 on 2023-04-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_details', '0009_alter_skills_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicdetails',
            name='resume',
            field=models.FileField(blank=True, default='', null=True, upload_to='media'),
        ),
    ]
